version: '3.9'

services:
  rosbridge:
    build:
      context: ./
    container_name: rosbridge_container
    # network_mode: host # Share the host network for easier access
    ports:
      - "9090:9090"
    restart: unless-stopped
    # environment:
    #   - ROS_DOMAIN_ID=0  # Adjust this if you're using a specific ROS domain ID
    #   - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ./rosbridge/launch:/root/rosbridge_launch
    command: ["ros2", "launch", "rosbridge_server", "rosbridge_websocket_launch.xml"]
