```puml
@startuml Arm Drawing
[*] --> WaitingForDrawing
WaitingForDrawing: Person draws
Move_Out : (not drawing)
Go_To_First_point : Move arm to first point
Move_In : (drawing)
Draw_Line : Arm moving through line
WaitingForDrawing --> Move_Out : Pressed Button
Move_Out -> Go_To_First_point : .5 second passed
Go_To_First_point -> Move_In : Reached first point
Move_In -> Draw_Line : 1 second passed
Draw_Line -> Move_Out : reached last point
Draw_Line --> WaitingForDrawing : Reached last line
@enduml